// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fusqicnzedothfunwtme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1c3FpY256ZWRvdGhmdW53dG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODI5NTQsImV4cCI6MjA2Njg1ODk1NH0.Jt_XCJvMjqSqK8XxppBEHUlRXjAOcufVrgBquXPK3rA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});